# This is a basic workflow to help you get started with Actions

name: discussion comment

# Controls when the workflow will run
on:
  discussion_comment:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          echo "$DISC"
        env:
          DISC: ${{ toJSON(github.event.discussion) }}
      - run: |
          echo "$COMM"
        env:
          COMM: ${{ toJSON(github.event.comment) }}
      - name: Transform timestamp
        id: timestamp-transform
        run: |
          echo "::set-output name=comment_created_at::$(date --date=$TIMESTAMP +%s)"
        env:
          TIMESTAMP: ${{ github.event.comment.created_at}}
      - run: |
          echo "$PAYLOAD"
        env:
          PAYLOAD: "{\"fallback\":\"New Comment on ${{ github.event.discussion.html_url}}\",\"pretext\":\"Comment on ${{ github.event.discussion.html_url}} \",\"author_name\":\"${{ github.event.comment.user.login }}\",\"author_link\":\"${{ github.event.comment.user.html_url }}\",\"author_icon\":\"${{ github.event.comment.user.avatar_url }}\",\"title\":\"Comment on ${{ github.event.discussion.html_url}}\",\"title_link\":\"${{ github.event.discussion.html_url}}\",\"text\":\"${{ github.event.comment.body}}\",\"footer\":\"${{ github.event.repository.html_url}}\",\"ts\":${{ steps.timestamp_transform.outputs.comment_created_at}}}"
      #- name: Send GitHub Action trigger data to Slack workflow
      #  id: slack
      #  uses: slackapi/slack-github-action@v1.15.0
      #  with:
      #    payload: "{\"fallback\":\"New Comment on ${{ github.event.discussion.html_url}}\",\"pretext\":\"Comment on ${{ github.event.discussion.html_url}} \",\"author_name\":\"${{ github.event.comment.user.login }}\",\"author_link\":\"${{ github.event.comment.user.html_url }}\",\"author_icon\":\"${{ github.event.comment.user.avatar_url }}\",\"title\":\"Comment on ${{ github.event.discussion.html_url}}\",\"title_link\":\"${{ github.event.discussion.html_url}}\",\"text\":\"${{ github.event.comment.body}}\",\"footer\":\"${{ github.event.repository.html_url}}\",\"ts\":${{ outputs.timestamp_transform.comment_created_at}}}"
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
