# This is a basic workflow to help you get started with Actions

name: discussion

# Controls when the workflow will run
on:
  discussion:
    types: 
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "$DISC"
        env:
          DISC: ${{ toJSON(github.event.discussion) }}
