# This is a basic workflow to help you get started with Actions

name: discussion

# Controls when the workflow will run
on:
  discussion:
    types: 
      - opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dump:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Transform timestamp
        id: timestamp_transform
        run: |
          echo "::set-output name=discussion_created_at::$(date --date=$TIMESTAMP +%s)"
        env:
          TIMESTAMP: ${{ github.event.discussion.created_at}}
      - name: Send to Slack
        id: slack
        run: |
          curl -d "$PAYLOAD" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PAYLOAD: "{\"attachments\":[{\"mrkdwn_in\":[\"text\"],\"fallback\":\"New Discussion opened at ${{ github.event.discussion.html_url}}\",\"author_name\":\"${{ github.event.discussion.user.login }}\",\"author_link\":\"${{ github.event.discussion.user.html_url }}\",\"author_icon\":\"${{ github.event.discussion.user.avatar_url }}\",\"title\":\"New Discussion opened: #${{github.event.discussion.number}} ${{ github.event.discussion.title}}\",\"title_link\":\"${{ github.event.discussion.html_url}}\",\"text\":\"${{ github.event.discussion.body}}\",\"footer\":\"${{ github.event.repository.full_name}}\",\"ts\":${{ steps.timestamp_transform.outputs.discussion_created_at}}}]}"
